sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

qiniuyun:
    oss:
      access-key: bjxv3VdZBTqbl-XFEc9_om74i1YlPSne9B_tRjBR
      secret-key: fKYRONIda8SGaOLmKthzg1_cLeNYyWu04lt7diZu
      bucket: swimmingliu